import { useEffect, useMemo, useState } from 'react';
import PageHeader from '../components/PageHeader.jsx';
import { api, endpoints } from '../services/api.js';

const emptyForm = { nombreMaterial: '', descripcion: '', stockActual: 0, stockMinimo: 0, unidadMedida: 'metro', estado: 'activo' };

export default function Materiales() {
  const [materiales, setMateriales] = useState([]);
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState(null);
  const [search, setSearch] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const load = async () => setMateriales(await api.get(endpoints.materiales));
  useEffect(() => { load().catch(err=>setError(err.message)); }, []);
  const filtered = useMemo(() => materiales.filter(m => `${m.nombreMaterial} ${m.descripcion}`.toLowerCase().includes(search.toLowerCase())), [materiales, search]);
  const submit = async (e) => { e.preventDefault(); setError(''); setMessage(''); const payload = { ...form, stockActual: Number(form.stockActual), stockMinimo: Number(form.stockMinimo), estado: form.estado.toLowerCase(), unidadMedida: form.unidadMedida.toLowerCase() }; try { if (editingId) await api.put(`${endpoints.materiales}/${editingId}`, payload); else await api.post(endpoints.materiales, payload); setMessage(editingId ? 'Material actualizado.' : 'Material registrado.'); setForm(emptyForm); setEditingId(null); await load(); } catch(err){setError(err.message);} };
  const edit = (m) => { setEditingId(m.idMaterial); setForm({ nombreMaterial:m.nombreMaterial||'', descripcion:m.descripcion||'', stockActual:m.stockActual||0, stockMinimo:m.stockMinimo||0, unidadMedida:m.unidadMedida||'metro', estado:m.estado||'activo' }); window.scrollTo({top:0,behavior:'smooth'}); };
  const remove = async (id) => { if(!confirm('¿Eliminar material?')) return; try { await api.delete(`${endpoints.materiales}/${id}`); setMessage('Material eliminado.'); await load(); } catch(err){setError(err.message);} };
  return <div className="fade-in"><PageHeader icon="bi-box-seam-fill" title="Inventario de materiales" subtitle="Control de stock, stock mínimo y alertas de producción." />{error&&<div className="alert alert-danger">{error}</div>}{message&&<div className="alert alert-success">{message}</div>}<form className="panel-card form-card module-form" onSubmit={submit}><h4>{editingId?'Editar material':'Nuevo material'}</h4><div className="form-grid"><div><label>Material</label><input className="form-control" value={form.nombreMaterial} onChange={e=>setForm({...form,nombreMaterial:e.target.value})} required /></div><div><label>Stock actual</label><input className="form-control" type="number" step="0.01" value={form.stockActual} onChange={e=>setForm({...form,stockActual:e.target.value})} required /></div><div><label>Stock mínimo</label><input className="form-control" type="number" step="0.01" value={form.stockMinimo} onChange={e=>setForm({...form,stockMinimo:e.target.value})} required /></div><div><label>Unidad</label><select className="form-select" value={form.unidadMedida} onChange={e=>setForm({...form,unidadMedida:e.target.value})}><option value="unidad">unidad</option><option value="metro">metro</option><option value="hoja">hoja</option><option value="kg">kg</option><option value="litro">litro</option><option value="paquete">paquete</option></select></div></div><label>Descripción</label><input className="form-control" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} /><button className="btn btn-primary mt-3" type="submit"><i className="bi bi-save"></i> {editingId?'Actualizar':'Guardar'}</button>{editingId&&<button className="btn btn-outline-dark mt-3 ms-2" type="button" onClick={()=>{setEditingId(null);setForm(emptyForm)}}>Cancelar</button>}</form><div className="panel-card mt-4"><div className="section-actions"><input className="form-control" placeholder="Buscar material..." value={search} onChange={e=>setSearch(e.target.value)} /><button className="btn btn-outline-dark" onClick={load}>Actualizar</button></div><div className="material-grid">{filtered.map(m=><article className={`material-card ${Number(m.stockActual)<=Number(m.stockMinimo)?'warning':''}`} key={m.idMaterial}><i className="bi bi-box2-heart"></i><h4>{m.nombreMaterial}</h4><p>Stock actual: <strong>{m.stockActual} {m.unidadMedida}</strong></p><p>Stock mínimo: {m.stockMinimo} {m.unidadMedida}</p><span>{Number(m.stockActual)<=Number(m.stockMinimo)?'Alerta de stock bajo':'Stock correcto'}</span><div className="table-actions mt-3"><button className="btn btn-sm btn-outline-dark" onClick={()=>edit(m)}>Editar</button><button className="btn btn-sm btn-outline-danger" onClick={()=>remove(m.idMaterial)}>Eliminar</button></div></article>)}</div></div></div>;
}
